// Server-render the REAL MCP SummaryView (src/views.tsx) for the Pellura fixture
// to a self-contained HTML document, and emit it as a TS module the Remotion demo
// embeds in an <iframe srcDoc>. This is the actual MCP report-summary markup —
// same component the mcp-app renders in the host iframe.
//
//   cd plugins/halo-mcp && npx tsx scripts/render-summary.tsx

import { renderToStaticMarkup } from "react-dom/server";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { createElement } from "react";
import { SummaryView, PublisherTableView } from "../src/views.tsx";
import { parseReport } from "../src/halo-types.ts";
import { findFixtureReport } from "../lib/halo-fixtures.ts";

const report = findFixtureReport("fixture_pellura_q1");
if (!report) throw new Error("Pellura fixture (fixture_pellura_q1) not found");
const parsed = parseReport(report);

// app is only used by Footer's onClick (export) — irrelevant for static markup.
const body = renderToStaticMarkup(createElement(SummaryView, { report: parsed, app: {} as never }));
const tableBody = renderToStaticMarkup(
  createElement(PublisherTableView, { report: parsed, app: {} as never }),
);

// Mirror the base of src/global.css so the inline-styled views inherit the right
// font + the few CSS vars some cards reference.
const BASE_CSS = `
:root{
  --color-text-primary:#1f2937;--color-text-secondary:#475569;--color-text-muted:#64748b;
  --color-background-primary:#ffffff;--color-background-secondary:#f8fafc;--color-background-tertiary:#f1f5f9;
  --color-border:#e2e8f0;--color-divider:#e5e7eb;
  --color-reach:#2C5CE1;--color-incremental:#0D8A5E;--color-frequency:#6D3BD1;--color-impressions:#475169;
  --color-danger:#dc2626;--color-warning:#d97706;
  --border-radius-sm:4px;--border-radius-md:6px;--border-radius-lg:10px;
  --font-sans:ui-sans-serif,system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;
  --font-mono:ui-monospace,SFMono-Regular,Menlo,monospace;
}
*{box-sizing:border-box;}
html,body{margin:0;font-family:var(--font-sans);font-size:14px;line-height:1.5;color:var(--color-text-primary);background:#ffffff;}
`;

const wrap = (b: string) =>
  `<!doctype html><html lang="en"><head><meta charset="utf-8"><style>${BASE_CSS}</style></head><body>${b}</body></html>`;
const doc = wrap(body);
const tableDoc = wrap(tableBody);

const dir = dirname(fileURLToPath(import.meta.url));
const sumOut = join(dir, "../../../demo/remotion/src/halo/pellura-summary-html.ts");
writeFileSync(
  sumOut,
  "// AUTO-GENERATED by plugins/halo-mcp/scripts/render-summary.tsx\n" +
    "// Real SSR output of the MCP SummaryView for the Pellura fixture.\n" +
    `export const PELLURA_SUMMARY_HTML = ${JSON.stringify(doc)};\n`,
);
const tblOut = join(dir, "../../../demo/remotion/src/halo/pellura-table-html.ts");
writeFileSync(
  tblOut,
  "// AUTO-GENERATED by plugins/halo-mcp/scripts/render-summary.tsx\n" +
    "// Real SSR output of the MCP PublisherTableView for the Pellura fixture.\n" +
    `export const PELLURA_TABLE_HTML = ${JSON.stringify(tableDoc)};\n`,
);
console.log(`Wrote summary (${doc.length}b) + table (${tableDoc.length}b)`);
